/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as SmartplaquesRouteImport } from './routes/smartplaques'
import { Route as ActivateIndexRouteImport } from './routes/activate.index'
import { Route as ActivateTokenRouteImport } from './routes/activate.$token'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminMoreRouteImport } from './routes/admin.more'
import { Route as AdminOfferingsRouteImport } from './routes/admin.offerings'
import { Route as AdminProvisioningRouteImport } from './routes/admin.provisioning'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppResultsRouteImport } from './routes/app.results'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as NSlugRouteImport } from './routes/n.$slug'
import { Route as OfferingsIndexRouteImport } from './routes/offerings.index'
import { Route as OfferingsSlugRouteImport } from './routes/offerings.$slug'
import { Route as QSlugRouteImport } from './routes/q.$slug'
import { Route as SetupSlugRouteImport } from './routes/setup.$slug'
import { Route as AdminBusinessesIndexRouteImport } from './routes/admin.businesses.index'
import { Route as AdminBusinessesIdRouteImport } from './routes/admin.businesses.$id'
import { Route as AdminInquiriesIndexRouteImport } from './routes/admin.inquiries.index'
import { Route as AdminInquiriesIdRouteImport } from './routes/admin.inquiries.$id'
import { Route as AdminNfcIndexRouteImport } from './routes/admin.nfc.index'
import { Route as AdminNfcBatchRouteImport } from './routes/admin.nfc.batch'
import { Route as AdminNfcReadRouteImport } from './routes/admin.nfc.read'
import { Route as AdminNfcVerifyRouteImport } from './routes/admin.nfc.verify'
import { Route as AdminNfcWriteRouteImport } from './routes/admin.nfc.write'
import { Route as AdminPlaquesIndexRouteImport } from './routes/admin.plaques.index'
import { Route as AppNfcIndexRouteImport } from './routes/app.nfc.index'
import { Route as AppNfcReadRouteImport } from './routes/app.nfc.read'
import { Route as AppNfcVerifyRouteImport } from './routes/app.nfc.verify'
import { Route as AppNfcWriteRouteImport } from './routes/app.nfc.write'
import { Route as AppPlaquesIndexRouteImport } from './routes/app.plaques.index'
import { Route as AppPlaquesIdRouteImport } from './routes/app.plaques.$id'
import { Route as AdminPlaquesIdIndexRouteImport } from './routes/admin.plaques.$id.index'
import { Route as AdminPlaquesIdProgramRouteImport } from './routes/admin.plaques.$id.program'
import { Route as AppNfcTagsIndexRouteImport } from './routes/app.nfc.tags.index'
import { Route as AppNfcTagsIdRouteImport } from './routes/app.nfc.tags.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartplaquesRoute = SmartplaquesRouteImport.update({
  id: '/smartplaques',
  path: '/smartplaques',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateIndexRoute = ActivateIndexRouteImport.update({
  id: '/activate/',
  path: '/activate/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateTokenRoute = ActivateTokenRouteImport.update({
  id: '/activate/$token',
  path: '/activate/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMoreRoute = AdminMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOfferingsRoute = AdminOfferingsRouteImport.update({
  id: '/offerings',
  path: '/offerings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvisioningRoute = AdminProvisioningRouteImport.update({
  id: '/provisioning',
  path: '/provisioning',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const NSlugRoute = NSlugRouteImport.update({
  id: '/n/$slug',
  path: '/n/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferingsIndexRoute = OfferingsIndexRouteImport.update({
  id: '/offerings/',
  path: '/offerings/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferingsSlugRoute = OfferingsSlugRouteImport.update({
  id: '/offerings/$slug',
  path: '/offerings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QSlugRoute = QSlugRouteImport.update({
  id: '/q/$slug',
  path: '/q/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupSlugRoute = SetupSlugRouteImport.update({
  id: '/setup/$slug',
  path: '/setup/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBusinessesIndexRoute = AdminBusinessesIndexRouteImport.update({
  id: '/businesses/',
  path: '/businesses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessesIdRoute = AdminBusinessesIdRouteImport.update({
  id: '/businesses/$id',
  path: '/businesses/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesIndexRoute = AdminInquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesIdRoute = AdminInquiriesIdRouteImport.update({
  id: '/inquiries/$id',
  path: '/inquiries/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNfcIndexRoute = AdminNfcIndexRouteImport.update({
  id: '/nfc/',
  path: '/nfc/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNfcBatchRoute = AdminNfcBatchRouteImport.update({
  id: '/nfc/batch',
  path: '/nfc/batch',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNfcReadRoute = AdminNfcReadRouteImport.update({
  id: '/nfc/read',
  path: '/nfc/read',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNfcVerifyRoute = AdminNfcVerifyRouteImport.update({
  id: '/nfc/verify',
  path: '/nfc/verify',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNfcWriteRoute = AdminNfcWriteRouteImport.update({
  id: '/nfc/write',
  path: '/nfc/write',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlaquesIndexRoute = AdminPlaquesIndexRouteImport.update({
  id: '/plaques/',
  path: '/plaques/',
  getParentRoute: () => AdminRoute,
} as any)
const AppNfcIndexRoute = AppNfcIndexRouteImport.update({
  id: '/nfc/',
  path: '/nfc/',
  getParentRoute: () => AppRoute,
} as any)
const AppNfcReadRoute = AppNfcReadRouteImport.update({
  id: '/nfc/read',
  path: '/nfc/read',
  getParentRoute: () => AppRoute,
} as any)
const AppNfcVerifyRoute = AppNfcVerifyRouteImport.update({
  id: '/nfc/verify',
  path: '/nfc/verify',
  getParentRoute: () => AppRoute,
} as any)
const AppNfcWriteRoute = AppNfcWriteRouteImport.update({
  id: '/nfc/write',
  path: '/nfc/write',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaquesIndexRoute = AppPlaquesIndexRouteImport.update({
  id: '/plaques/',
  path: '/plaques/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaquesIdRoute = AppPlaquesIdRouteImport.update({
  id: '/plaques/$id',
  path: '/plaques/$id',
  getParentRoute: () => AppRoute,
} as any)
const AdminPlaquesIdIndexRoute = AdminPlaquesIdIndexRouteImport.update({
  id: '/plaques/$id/',
  path: '/plaques/$id/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlaquesIdProgramRoute = AdminPlaquesIdProgramRouteImport.update({
  id: '/plaques/$id/program',
  path: '/plaques/$id/program',
  getParentRoute: () => AdminRoute,
} as any)
const AppNfcTagsIndexRoute = AppNfcTagsIndexRouteImport.update({
  id: '/nfc/tags/',
  path: '/nfc/tags/',
  getParentRoute: () => AppRoute,
} as any)
const AppNfcTagsIdRoute = AppNfcTagsIdRouteImport.update({
  id: '/nfc/tags/$id',
  path: '/nfc/tags/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/smartplaques': typeof SmartplaquesRoute
  '/activate/$token': typeof ActivateTokenRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/offerings': typeof AdminOfferingsRoute
  '/admin/provisioning': typeof AdminProvisioningRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/app/activity': typeof AppActivityRoute
  '/app/results': typeof AppResultsRoute
  '/app/settings': typeof AppSettingsRoute
  '/n/$slug': typeof NSlugRoute
  '/offerings/$slug': typeof OfferingsSlugRoute
  '/q/$slug': typeof QSlugRoute
  '/setup/$slug': typeof SetupSlugRoute
  '/activate/': typeof ActivateIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/offerings/': typeof OfferingsIndexRoute
  '/admin/businesses/$id': typeof AdminBusinessesIdRoute
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/nfc/batch': typeof AdminNfcBatchRoute
  '/admin/nfc/read': typeof AdminNfcReadRoute
  '/admin/nfc/verify': typeof AdminNfcVerifyRoute
  '/admin/nfc/write': typeof AdminNfcWriteRoute
  '/app/nfc/read': typeof AppNfcReadRoute
  '/app/nfc/verify': typeof AppNfcVerifyRoute
  '/app/nfc/write': typeof AppNfcWriteRoute
  '/app/plaques/$id': typeof AppPlaquesIdRoute
  '/admin/businesses/': typeof AdminBusinessesIndexRoute
  '/admin/inquiries/': typeof AdminInquiriesIndexRoute
  '/admin/nfc/': typeof AdminNfcIndexRoute
  '/admin/plaques/': typeof AdminPlaquesIndexRoute
  '/app/nfc/': typeof AppNfcIndexRoute
  '/app/plaques/': typeof AppPlaquesIndexRoute
  '/admin/plaques/$id/program': typeof AdminPlaquesIdProgramRoute
  '/app/nfc/tags/$id': typeof AppNfcTagsIdRoute
  '/admin/plaques/$id/': typeof AdminPlaquesIdIndexRoute
  '/app/nfc/tags/': typeof AppNfcTagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/smartplaques': typeof SmartplaquesRoute
  '/activate/$token': typeof ActivateTokenRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/offerings': typeof AdminOfferingsRoute
  '/admin/provisioning': typeof AdminProvisioningRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/app/activity': typeof AppActivityRoute
  '/app/results': typeof AppResultsRoute
  '/app/settings': typeof AppSettingsRoute
  '/n/$slug': typeof NSlugRoute
  '/offerings/$slug': typeof OfferingsSlugRoute
  '/q/$slug': typeof QSlugRoute
  '/setup/$slug': typeof SetupSlugRoute
  '/activate': typeof ActivateIndexRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/offerings': typeof OfferingsIndexRoute
  '/admin/businesses/$id': typeof AdminBusinessesIdRoute
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/nfc/batch': typeof AdminNfcBatchRoute
  '/admin/nfc/read': typeof AdminNfcReadRoute
  '/admin/nfc/verify': typeof AdminNfcVerifyRoute
  '/admin/nfc/write': typeof AdminNfcWriteRoute
  '/app/nfc/read': typeof AppNfcReadRoute
  '/app/nfc/verify': typeof AppNfcVerifyRoute
  '/app/nfc/write': typeof AppNfcWriteRoute
  '/app/plaques/$id': typeof AppPlaquesIdRoute
  '/admin/businesses': typeof AdminBusinessesIndexRoute
  '/admin/inquiries': typeof AdminInquiriesIndexRoute
  '/admin/nfc': typeof AdminNfcIndexRoute
  '/admin/plaques': typeof AdminPlaquesIndexRoute
  '/app/nfc': typeof AppNfcIndexRoute
  '/app/plaques': typeof AppPlaquesIndexRoute
  '/admin/plaques/$id/program': typeof AdminPlaquesIdProgramRoute
  '/app/nfc/tags/$id': typeof AppNfcTagsIdRoute
  '/admin/plaques/$id': typeof AdminPlaquesIdIndexRoute
  '/app/nfc/tags': typeof AppNfcTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/smartplaques': typeof SmartplaquesRoute
  '/activate/$token': typeof ActivateTokenRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/more': typeof AdminMoreRoute
  '/admin/offerings': typeof AdminOfferingsRoute
  '/admin/provisioning': typeof AdminProvisioningRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/app/activity': typeof AppActivityRoute
  '/app/results': typeof AppResultsRoute
  '/app/settings': typeof AppSettingsRoute
  '/n/$slug': typeof NSlugRoute
  '/offerings/$slug': typeof OfferingsSlugRoute
  '/q/$slug': typeof QSlugRoute
  '/setup/$slug': typeof SetupSlugRoute
  '/activate/': typeof ActivateIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/offerings/': typeof OfferingsIndexRoute
  '/admin/businesses/$id': typeof AdminBusinessesIdRoute
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/nfc/batch': typeof AdminNfcBatchRoute
  '/admin/nfc/read': typeof AdminNfcReadRoute
  '/admin/nfc/verify': typeof AdminNfcVerifyRoute
  '/admin/nfc/write': typeof AdminNfcWriteRoute
  '/app/nfc/read': typeof AppNfcReadRoute
  '/app/nfc/verify': typeof AppNfcVerifyRoute
  '/app/nfc/write': typeof AppNfcWriteRoute
  '/app/plaques/$id': typeof AppPlaquesIdRoute
  '/admin/businesses/': typeof AdminBusinessesIndexRoute
  '/admin/inquiries/': typeof AdminInquiriesIndexRoute
  '/admin/nfc/': typeof AdminNfcIndexRoute
  '/admin/plaques/': typeof AdminPlaquesIndexRoute
  '/app/nfc/': typeof AppNfcIndexRoute
  '/app/plaques/': typeof AppPlaquesIndexRoute
  '/admin/plaques/$id/program': typeof AdminPlaquesIdProgramRoute
  '/app/nfc/tags/$id': typeof AppNfcTagsIdRoute
  '/admin/plaques/$id/': typeof AdminPlaquesIdIndexRoute
  '/app/nfc/tags/': typeof AppNfcTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/demo'
    | '/smartplaques'
    | '/activate/$token'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/more'
    | '/admin/offerings'
    | '/admin/provisioning'
    | '/admin/settings'
    | '/admin/setup'
    | '/app/activity'
    | '/app/results'
    | '/app/settings'
    | '/n/$slug'
    | '/offerings/$slug'
    | '/q/$slug'
    | '/setup/$slug'
    | '/activate/'
    | '/admin/'
    | '/app/'
    | '/offerings/'
    | '/admin/businesses/$id'
    | '/admin/inquiries/$id'
    | '/admin/nfc/batch'
    | '/admin/nfc/read'
    | '/admin/nfc/verify'
    | '/admin/nfc/write'
    | '/app/nfc/read'
    | '/app/nfc/verify'
    | '/app/nfc/write'
    | '/app/plaques/$id'
    | '/admin/businesses/'
    | '/admin/inquiries/'
    | '/admin/nfc/'
    | '/admin/plaques/'
    | '/app/nfc/'
    | '/app/plaques/'
    | '/admin/plaques/$id/program'
    | '/app/nfc/tags/$id'
    | '/admin/plaques/$id/'
    | '/app/nfc/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo'
    | '/smartplaques'
    | '/activate/$token'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/more'
    | '/admin/offerings'
    | '/admin/provisioning'
    | '/admin/settings'
    | '/admin/setup'
    | '/app/activity'
    | '/app/results'
    | '/app/settings'
    | '/n/$slug'
    | '/offerings/$slug'
    | '/q/$slug'
    | '/setup/$slug'
    | '/activate'
    | '/admin'
    | '/app'
    | '/offerings'
    | '/admin/businesses/$id'
    | '/admin/inquiries/$id'
    | '/admin/nfc/batch'
    | '/admin/nfc/read'
    | '/admin/nfc/verify'
    | '/admin/nfc/write'
    | '/app/nfc/read'
    | '/app/nfc/verify'
    | '/app/nfc/write'
    | '/app/plaques/$id'
    | '/admin/businesses'
    | '/admin/inquiries'
    | '/admin/nfc'
    | '/admin/plaques'
    | '/app/nfc'
    | '/app/plaques'
    | '/admin/plaques/$id/program'
    | '/app/nfc/tags/$id'
    | '/admin/plaques/$id'
    | '/app/nfc/tags'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/demo'
    | '/smartplaques'
    | '/activate/$token'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/more'
    | '/admin/offerings'
    | '/admin/provisioning'
    | '/admin/settings'
    | '/admin/setup'
    | '/app/activity'
    | '/app/results'
    | '/app/settings'
    | '/n/$slug'
    | '/offerings/$slug'
    | '/q/$slug'
    | '/setup/$slug'
    | '/activate/'
    | '/admin/'
    | '/app/'
    | '/offerings/'
    | '/admin/businesses/$id'
    | '/admin/inquiries/$id'
    | '/admin/nfc/batch'
    | '/admin/nfc/read'
    | '/admin/nfc/verify'
    | '/admin/nfc/write'
    | '/app/nfc/read'
    | '/app/nfc/verify'
    | '/app/nfc/write'
    | '/app/plaques/$id'
    | '/admin/businesses/'
    | '/admin/inquiries/'
    | '/admin/nfc/'
    | '/admin/plaques/'
    | '/app/nfc/'
    | '/app/plaques/'
    | '/admin/plaques/$id/program'
    | '/app/nfc/tags/$id'
    | '/admin/plaques/$id/'
    | '/app/nfc/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRoute
  SmartplaquesRoute: typeof SmartplaquesRoute
  ActivateTokenRoute: typeof ActivateTokenRoute
  NSlugRoute: typeof NSlugRoute
  OfferingsSlugRoute: typeof OfferingsSlugRoute
  QSlugRoute: typeof QSlugRoute
  SetupSlugRoute: typeof SetupSlugRoute
  ActivateIndexRoute: typeof ActivateIndexRoute
  OfferingsIndexRoute: typeof OfferingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smartplaques': {
      id: '/smartplaques'
      path: '/smartplaques'
      fullPath: '/smartplaques'
      preLoaderRoute: typeof SmartplaquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate/': {
      id: '/activate/'
      path: '/activate'
      fullPath: '/activate/'
      preLoaderRoute: typeof ActivateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate/$token': {
      id: '/activate/$token'
      path: '/activate/$token'
      fullPath: '/activate/$token'
      preLoaderRoute: typeof ActivateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/more': {
      id: '/admin/more'
      path: '/more'
      fullPath: '/admin/more'
      preLoaderRoute: typeof AdminMoreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offerings': {
      id: '/admin/offerings'
      path: '/offerings'
      fullPath: '/admin/offerings'
      preLoaderRoute: typeof AdminOfferingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/provisioning': {
      id: '/admin/provisioning'
      path: '/provisioning'
      fullPath: '/admin/provisioning'
      preLoaderRoute: typeof AdminProvisioningRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/results': {
      id: '/app/results'
      path: '/results'
      fullPath: '/app/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/n/$slug': {
      id: '/n/$slug'
      path: '/n/$slug'
      fullPath: '/n/$slug'
      preLoaderRoute: typeof NSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerings/': {
      id: '/offerings/'
      path: '/offerings'
      fullPath: '/offerings/'
      preLoaderRoute: typeof OfferingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerings/$slug': {
      id: '/offerings/$slug'
      path: '/offerings/$slug'
      fullPath: '/offerings/$slug'
      preLoaderRoute: typeof OfferingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$slug': {
      id: '/q/$slug'
      path: '/q/$slug'
      fullPath: '/q/$slug'
      preLoaderRoute: typeof QSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/$slug': {
      id: '/setup/$slug'
      path: '/setup/$slug'
      fullPath: '/setup/$slug'
      preLoaderRoute: typeof SetupSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/businesses/': {
      id: '/admin/businesses/'
      path: '/businesses'
      fullPath: '/admin/businesses/'
      preLoaderRoute: typeof AdminBusinessesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/businesses/$id': {
      id: '/admin/businesses/$id'
      path: '/businesses/$id'
      fullPath: '/admin/businesses/$id'
      preLoaderRoute: typeof AdminBusinessesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries/': {
      id: '/admin/inquiries/'
      path: '/inquiries'
      fullPath: '/admin/inquiries/'
      preLoaderRoute: typeof AdminInquiriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries/$id': {
      id: '/admin/inquiries/$id'
      path: '/inquiries/$id'
      fullPath: '/admin/inquiries/$id'
      preLoaderRoute: typeof AdminInquiriesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nfc/': {
      id: '/admin/nfc/'
      path: '/nfc'
      fullPath: '/admin/nfc/'
      preLoaderRoute: typeof AdminNfcIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nfc/batch': {
      id: '/admin/nfc/batch'
      path: '/nfc/batch'
      fullPath: '/admin/nfc/batch'
      preLoaderRoute: typeof AdminNfcBatchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nfc/read': {
      id: '/admin/nfc/read'
      path: '/nfc/read'
      fullPath: '/admin/nfc/read'
      preLoaderRoute: typeof AdminNfcReadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nfc/verify': {
      id: '/admin/nfc/verify'
      path: '/nfc/verify'
      fullPath: '/admin/nfc/verify'
      preLoaderRoute: typeof AdminNfcVerifyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nfc/write': {
      id: '/admin/nfc/write'
      path: '/nfc/write'
      fullPath: '/admin/nfc/write'
      preLoaderRoute: typeof AdminNfcWriteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plaques/': {
      id: '/admin/plaques/'
      path: '/plaques'
      fullPath: '/admin/plaques/'
      preLoaderRoute: typeof AdminPlaquesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/nfc/': {
      id: '/app/nfc/'
      path: '/nfc'
      fullPath: '/app/nfc/'
      preLoaderRoute: typeof AppNfcIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nfc/read': {
      id: '/app/nfc/read'
      path: '/nfc/read'
      fullPath: '/app/nfc/read'
      preLoaderRoute: typeof AppNfcReadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nfc/verify': {
      id: '/app/nfc/verify'
      path: '/nfc/verify'
      fullPath: '/app/nfc/verify'
      preLoaderRoute: typeof AppNfcVerifyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nfc/write': {
      id: '/app/nfc/write'
      path: '/nfc/write'
      fullPath: '/app/nfc/write'
      preLoaderRoute: typeof AppNfcWriteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plaques/': {
      id: '/app/plaques/'
      path: '/plaques'
      fullPath: '/app/plaques/'
      preLoaderRoute: typeof AppPlaquesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plaques/$id': {
      id: '/app/plaques/$id'
      path: '/plaques/$id'
      fullPath: '/app/plaques/$id'
      preLoaderRoute: typeof AppPlaquesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/plaques/$id/': {
      id: '/admin/plaques/$id/'
      path: '/plaques/$id'
      fullPath: '/admin/plaques/$id/'
      preLoaderRoute: typeof AdminPlaquesIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plaques/$id/program': {
      id: '/admin/plaques/$id/program'
      path: '/plaques/$id/program'
      fullPath: '/admin/plaques/$id/program'
      preLoaderRoute: typeof AdminPlaquesIdProgramRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/nfc/tags/': {
      id: '/app/nfc/tags/'
      path: '/nfc/tags'
      fullPath: '/app/nfc/tags/'
      preLoaderRoute: typeof AppNfcTagsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nfc/tags/$id': {
      id: '/app/nfc/tags/$id'
      path: '/nfc/tags/$id'
      fullPath: '/app/nfc/tags/$id'
      preLoaderRoute: typeof AppNfcTagsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminMoreRoute: typeof AdminMoreRoute
  AdminOfferingsRoute: typeof AdminOfferingsRoute
  AdminProvisioningRoute: typeof AdminProvisioningRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBusinessesIdRoute: typeof AdminBusinessesIdRoute
  AdminInquiriesIdRoute: typeof AdminInquiriesIdRoute
  AdminNfcBatchRoute: typeof AdminNfcBatchRoute
  AdminNfcReadRoute: typeof AdminNfcReadRoute
  AdminNfcVerifyRoute: typeof AdminNfcVerifyRoute
  AdminNfcWriteRoute: typeof AdminNfcWriteRoute
  AdminBusinessesIndexRoute: typeof AdminBusinessesIndexRoute
  AdminInquiriesIndexRoute: typeof AdminInquiriesIndexRoute
  AdminNfcIndexRoute: typeof AdminNfcIndexRoute
  AdminPlaquesIndexRoute: typeof AdminPlaquesIndexRoute
  AdminPlaquesIdProgramRoute: typeof AdminPlaquesIdProgramRoute
  AdminPlaquesIdIndexRoute: typeof AdminPlaquesIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminMoreRoute: AdminMoreRoute,
  AdminOfferingsRoute: AdminOfferingsRoute,
  AdminProvisioningRoute: AdminProvisioningRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBusinessesIdRoute: AdminBusinessesIdRoute,
  AdminInquiriesIdRoute: AdminInquiriesIdRoute,
  AdminNfcBatchRoute: AdminNfcBatchRoute,
  AdminNfcReadRoute: AdminNfcReadRoute,
  AdminNfcVerifyRoute: AdminNfcVerifyRoute,
  AdminNfcWriteRoute: AdminNfcWriteRoute,
  AdminBusinessesIndexRoute: AdminBusinessesIndexRoute,
  AdminInquiriesIndexRoute: AdminInquiriesIndexRoute,
  AdminNfcIndexRoute: AdminNfcIndexRoute,
  AdminPlaquesIndexRoute: AdminPlaquesIndexRoute,
  AdminPlaquesIdProgramRoute: AdminPlaquesIdProgramRoute,
  AdminPlaquesIdIndexRoute: AdminPlaquesIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppResultsRoute: typeof AppResultsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppNfcReadRoute: typeof AppNfcReadRoute
  AppNfcVerifyRoute: typeof AppNfcVerifyRoute
  AppNfcWriteRoute: typeof AppNfcWriteRoute
  AppPlaquesIdRoute: typeof AppPlaquesIdRoute
  AppNfcIndexRoute: typeof AppNfcIndexRoute
  AppPlaquesIndexRoute: typeof AppPlaquesIndexRoute
  AppNfcTagsIdRoute: typeof AppNfcTagsIdRoute
  AppNfcTagsIndexRoute: typeof AppNfcTagsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppResultsRoute: AppResultsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppNfcReadRoute: AppNfcReadRoute,
  AppNfcVerifyRoute: AppNfcVerifyRoute,
  AppNfcWriteRoute: AppNfcWriteRoute,
  AppPlaquesIdRoute: AppPlaquesIdRoute,
  AppNfcIndexRoute: AppNfcIndexRoute,
  AppPlaquesIndexRoute: AppPlaquesIndexRoute,
  AppNfcTagsIdRoute: AppNfcTagsIdRoute,
  AppNfcTagsIndexRoute: AppNfcTagsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRoute,
  SmartplaquesRoute: SmartplaquesRoute,
  ActivateTokenRoute: ActivateTokenRoute,
  NSlugRoute: NSlugRoute,
  OfferingsSlugRoute: OfferingsSlugRoute,
  QSlugRoute: QSlugRoute,
  SetupSlugRoute: SetupSlugRoute,
  ActivateIndexRoute: ActivateIndexRoute,
  OfferingsIndexRoute: OfferingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
