/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ActivateTokenRouteImport } from './routes/activate.$token'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppResultsRouteImport } from './routes/app.results'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as NSlugRouteImport } from './routes/n.$slug'
import { Route as AppPlaquesIndexRouteImport } from './routes/app.plaques.index'
import { Route as AppPlaquesIdRouteImport } from './routes/app.plaques.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateTokenRoute = ActivateTokenRouteImport.update({
  id: '/activate/$token',
  path: '/activate/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const NSlugRoute = NSlugRouteImport.update({
  id: '/n/$slug',
  path: '/n/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPlaquesIndexRoute = AppPlaquesIndexRouteImport.update({
  id: '/plaques/',
  path: '/plaques/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaquesIdRoute = AppPlaquesIdRouteImport.update({
  id: '/plaques/$id',
  path: '/plaques/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/activate/$token': typeof ActivateTokenRoute
  '/app/activity': typeof AppActivityRoute
  '/app/results': typeof AppResultsRoute
  '/app/settings': typeof AppSettingsRoute
  '/n/$slug': typeof NSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/plaques/$id': typeof AppPlaquesIdRoute
  '/app/plaques/': typeof AppPlaquesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate/$token': typeof ActivateTokenRoute
  '/app/activity': typeof AppActivityRoute
  '/app/results': typeof AppResultsRoute
  '/app/settings': typeof AppSettingsRoute
  '/n/$slug': typeof NSlugRoute
  '/app': typeof AppIndexRoute
  '/app/plaques/$id': typeof AppPlaquesIdRoute
  '/app/plaques': typeof AppPlaquesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/activate/$token': typeof ActivateTokenRoute
  '/app/activity': typeof AppActivityRoute
  '/app/results': typeof AppResultsRoute
  '/app/settings': typeof AppSettingsRoute
  '/n/$slug': typeof NSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/plaques/$id': typeof AppPlaquesIdRoute
  '/app/plaques/': typeof AppPlaquesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/activate/$token'
    | '/app/activity'
    | '/app/results'
    | '/app/settings'
    | '/n/$slug'
    | '/app/'
    | '/app/plaques/$id'
    | '/app/plaques/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate/$token'
    | '/app/activity'
    | '/app/results'
    | '/app/settings'
    | '/n/$slug'
    | '/app'
    | '/app/plaques/$id'
    | '/app/plaques'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/activate/$token'
    | '/app/activity'
    | '/app/results'
    | '/app/settings'
    | '/n/$slug'
    | '/app/'
    | '/app/plaques/$id'
    | '/app/plaques/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ActivateTokenRoute: typeof ActivateTokenRoute
  NSlugRoute: typeof NSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate/$token': {
      id: '/activate/$token'
      path: '/activate/$token'
      fullPath: '/activate/$token'
      preLoaderRoute: typeof ActivateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/results': {
      id: '/app/results'
      path: '/results'
      fullPath: '/app/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/n/$slug': {
      id: '/n/$slug'
      path: '/n/$slug'
      fullPath: '/n/$slug'
      preLoaderRoute: typeof NSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/plaques/': {
      id: '/app/plaques/'
      path: '/plaques'
      fullPath: '/app/plaques/'
      preLoaderRoute: typeof AppPlaquesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plaques/$id': {
      id: '/app/plaques/$id'
      path: '/plaques/$id'
      fullPath: '/app/plaques/$id'
      preLoaderRoute: typeof AppPlaquesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppResultsRoute: typeof AppResultsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPlaquesIdRoute: typeof AppPlaquesIdRoute
  AppPlaquesIndexRoute: typeof AppPlaquesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppResultsRoute: AppResultsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppPlaquesIdRoute: AppPlaquesIdRoute,
  AppPlaquesIndexRoute: AppPlaquesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ActivateTokenRoute: ActivateTokenRoute,
  NSlugRoute: NSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
